### ISSUE TITLE
Link for the Navbar Element Help and Login isn't working

### ISSUE THREAD

**Issue by darshanhande11** [aviraltandon21/scripture#1]
### Ways to reproduce the issue

- Go to [Scripture](http://scripture.host20.uk/index.php)
- Click on the `About Us` Nav Element
- AboutUs page opens
- Now, click on the `Help` Nav Element, it doesn't open (the link is missing)
- Now, also click on the `Login` Nav Element, it doesn't open (the link is missing)

### Expected Behaviour

- Clicking on the `Help` should redirect users from `About Us` to the help page.
- After clicking on `Login`, a pop-up to login should appear.

**Comment by aviraltandon21** [comment]
Thanks for pointing out the issue. Its been fixed now.
